version: "3"

services:
  nginx: 
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: guisfits/fullcycle-docker-nginx
    container_name: nginx
    networks:
      - fullcycle-docker
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    image: guisfits/fullcycle-docker-node:prod
    container_name: app
    entrypoint: wait-for db:3306 -t 50 -- npm run start
    networks:
      - fullcycle-docker 
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:8.0.32
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    volumes: 
      - ./mysql_data:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - fullcycle-docker

networks:
  fullcycle-docker:
    driver: bridge 
